---

sudo: required
language: python
python:
  - "2.7"
script:
  - pip install ansible
  - ansible-playbook -i tests/inventory -vvvv tests/test.yml'
  - >
      ansible-playbook -i tests/inventory -vvvv tests/test.yml --limit xenial'
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
