---

- name: Install LXD with snap
  shell: snap install lxd

- name: Install LXD
  apt:
    name: '{{ item }}'
    state: latest
    default_release: xenial-backports
  with_items: '{{ lxd_packages }}'

- name: Add users to lxd group
  user:
    name: '{{ item }}'
    groups: lxd
    append: true
  with_items: '{{ lxd_users }}'
  register: lxd_group_users_status
