---
- name: Ensure APT LXD repository (stable)
  apt_repository: repo="ppa:ubuntu-lxc/lxd-stable" update_cache="yes"
  when: lxd_apt_stable_repo

- name: Install LXD
  package: name={{ item }} state=present
  with_items: '{{ lxd_packages }}'

- name: Add users to lxd group
  user: name={{ item }} groups=lxd append=yes
  with_items: '{{ lxd_users }}'
