---

- name: Ensure there is no  lxd installed from repo
  apt:
    name: '{{ item }}'
  with_items:
    - lxd
    - lxd-client

- name: Install LXD with snap
  shell: snap install {{ item }}
  with_items:
    - lxd --channel=3.0
    - lxd
  changed_when: false

- name: Add users to lxd group
  user:
    name: '{{ item }}'
    groups: lxd
    append: true
  with_items: '{{ lxd_users }}'
  register: lxd_group_users_status
