---

- name: Ensure there is no  lxd installed from repo
  apt:
    name: '{{ item }}'
    state: absent
  with_items:
    - lxd
    - lxd-client

- name: Create lxd group
  group:
    name: lxd
    state: present

- name: Add users to lxd group
  user:
    name: '{{ item }}'
    groups: lxd
    append: true
  with_items: '{{ lxd_users }}'
  register: lxd_group_users_status

- name: Install LXD with snap
  shell: snap install {{ item }}
  with_items:
    - lxd --channel=3.0
  when: lxd_install == "true"
  changed_when: false
